[[CasADi]]
arch = "aarch64"
git-tree-sha1 = "aa054767a4c572ead0cd12bd5da6f40b7b53db38"
os = "macos"

    [[CasADi.download]]
    sha256 = "8908a535ddfa8629c8907cbd9846058992dc532ef8de93ac8dc12a23db24ca4f"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.aarch64-apple-darwin.tar.gz"
[[CasADi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cda34bf5d5e04468a4726d56d99d3e142d991e8"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "d686a7d78e7d477a8edf955f81f600f2827537c241e741974c043d8b0cb75ec6"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.aarch64-linux-gnu-cxx11.tar.gz"
[[CasADi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ca616acf4573299c384fdfd3bc07be4958de72a"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "eb34e454fc7b63000df052358d133bc4dcfedad8809143084a1b7d9abdbbcb03"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.aarch64-linux-musl-cxx11.tar.gz"
[[CasADi]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "909581ed87bb0f3cc98f3f8fac2c134c04ee2579"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "9d2153e539fa7598d7d294c7608c8db1d98f3175728207b063771f64574cb71c"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CasADi]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7eeeda99b2b948e760c07297f72312735d81b0c1"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "a73412eae680cd5d0b399fe21708ee1f209157ccbae960c3cd5553d8bab6ff7c"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CasADi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbad2a81bb2f2b02a829db99d2b4734fca94ada2"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "a2bd5826c53c2295cf191c0fdf474bb980095aa83ad10b27335e217f27e4dc3c"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CasADi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6521efd7d63e06d6e4228f984b0fc5d359a48745"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "1ab58280361c2a8ab5b15a1b5ec0c2c922990d91d6f34a2daa7708bb2d53e8c4"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CasADi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "448c01e41a8c27f159b08d73879d0d5c92f77e67"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "7cb281abb4e6f7127e5791c5007ed1e0088cf04af0fe569d184eea398ffa87b1"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.i686-linux-gnu-cxx11.tar.gz"
[[CasADi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97bd05ca570801c829daa74a77deb13b9c71cb54"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "2b578710d5c1fb68d96d0a90819313a34aab5eef165248634bf05676972c8052"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.i686-linux-musl-cxx11.tar.gz"
[[CasADi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "888bfd62810bf34ea0dbca2171132e80c1ada34f"
os = "windows"

    [[CasADi.download]]
    sha256 = "11e12370932d4f0e1afbe6d0a1265d7134ca59d055471db5306ee02fb3166746"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.i686-w64-mingw32-cxx11.tar.gz"
[[CasADi]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddc3e7f876e07e1ae94ccaaff3b38dc1180e8fe6"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "b6c4c73c6ef079a978117219b215a790e60809b965afe3877e5de8eff7be33b4"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CasADi]]
arch = "x86_64"
git-tree-sha1 = "b9e36548be74b9d76d9496f7c3d6b3724249e1ed"
os = "macos"

    [[CasADi.download]]
    sha256 = "c3eb186cd32cd619f80dc5b422672c60ecd7d0432306b878159e1968bf083a7e"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.x86_64-apple-darwin.tar.gz"
[[CasADi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1dd850853758e1548aa3e94edbf49cc03c06e81d"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "41d2eae24dd81a0e73095ab545c78534ae5dca37e0b735ea689aaaf0c1f084cc"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.x86_64-linux-gnu-cxx11.tar.gz"
[[CasADi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "227595091a56d0c43c2dd33a9be3334a112b2d7b"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "0409b39b0c5603a68315ad88d1437a4236f34747f66461782ecb2f206f7803e0"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.x86_64-linux-musl-cxx11.tar.gz"
[[CasADi]]
arch = "x86_64"
git-tree-sha1 = "eb4eeba7a77956640f134e6a03b06a6a3cfc44e1"
os = "freebsd"

    [[CasADi.download]]
    sha256 = "5d67d5a61cf1495797c520ff914cc983f2c1e39d97e223220c8a0ada4fa7d9bc"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.x86_64-unknown-freebsd.tar.gz"
[[CasADi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f389b5686302a6c57074d78f998600416bddecb2"
os = "windows"

    [[CasADi.download]]
    sha256 = "bf19f836237c8f42cb280ae57783d318d508c3662a673fe5f86e0876922e0243"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.2+0/CasADi.v3.7.2.x86_64-w64-mingw32-cxx11.tar.gz"
