[[CasADi]]
arch = "aarch64"
git-tree-sha1 = "8a5dd46405d1cee170912f8d452095ed3dd0a2e8"
os = "macos"

    [[CasADi.download]]
    sha256 = "bc4d0e2ddc3a6cf55c6a79443636e574338dbcad014d8ceb53a277f5abaece75"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.aarch64-apple-darwin.tar.gz"
[[CasADi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22184d76ca2c48a2723910a9eb48f12f53dca005"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "8b78f8ad5e25e87a7892d05817a3c1796704129b51811e54eef2d4fd791a8c00"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.aarch64-linux-gnu-cxx11.tar.gz"
[[CasADi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af1fd8ac95a9d59226277773e4508c476aabc29b"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "cdbd6654afa4c0f6dbc8e62041e2d37e160720ce2ddc07197eb11eaf5c5d4fe3"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.aarch64-linux-musl-cxx11.tar.gz"
[[CasADi]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14082e4867a33ad915cf451651e8c4d479077ede"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "9ecf09d8de982522789d27a8efe163d31ce8b216e124428b75875050cad100c8"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[CasADi]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7212de3da7caf556210a3fcd358c9f60e1f1e2d"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "87962fdf8d01774897ff95145a96c7ab2a3b7a1c5ddffad6d9e170f941a34b69"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[CasADi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f7f2ed0f8bb9c57bb3a31131c2b951f7818692f"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "814321d3d8ca27bc1f290922502bc254ddd347387e5cc051aac1125e720d909d"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[CasADi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6db8e7751aa96a72b60b60043cd0c21a4da9355d"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "1a4aaebae7b21b12b03eecd7bba56f1ebf5ad13af91eea97156950d4ffa6220b"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[CasADi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2e5b71de869f495041e6184ee79d75ba97f35fc"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "6fe53cd35a50b0117c36c709d57d4e2bb9eceb9bd40ea1c36652c0dd82f4b1b4"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.i686-linux-gnu-cxx11.tar.gz"
[[CasADi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bdb2a17538d0c53fd8403f8a819e0647ba6caba"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "83eb8e2a3c754c8914213b4330a35889c858ff60d185f29f91198eac2716a812"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.i686-linux-musl-cxx11.tar.gz"
[[CasADi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "864213be440ef9558036b7f7fd391c1ccd0414e5"
os = "windows"

    [[CasADi.download]]
    sha256 = "c65fa545177296786c19d322247b512086531e0b7b200a1a3cde530399c668f5"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.i686-w64-mingw32-cxx11.tar.gz"
[[CasADi]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42aee14cecfe99c41360cf14b2a740e837d22144"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "da87d801131fb7c73e750d30bba5373e8d0310fabfcc3685a04f1c34f6db4f24"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[CasADi]]
arch = "x86_64"
git-tree-sha1 = "0988558b1af209dfc076eb523fbb5f500b1fd01e"
os = "macos"

    [[CasADi.download]]
    sha256 = "b6047ed01180268f378f2da0ae491c8ca2aebb484aa6be5dcfc9499e0397c22a"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.x86_64-apple-darwin.tar.gz"
[[CasADi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d045263ffe9e17a536b9b9d293e9fc3e8402f898"
libc = "glibc"
os = "linux"

    [[CasADi.download]]
    sha256 = "f9779ea5bebf64863c54b3e0cb59ddcf503db6f396dfcd5321ffe2773d6a7a53"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.x86_64-linux-gnu-cxx11.tar.gz"
[[CasADi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97143dc5a93acee8f2c3aad30660ba75fa6cb046"
libc = "musl"
os = "linux"

    [[CasADi.download]]
    sha256 = "e4ea74e1f45a10af117239bfd06fba586f93a4624571b79641ac6f080576399f"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.x86_64-linux-musl-cxx11.tar.gz"
[[CasADi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8339aa9596ddc3a80d9c950fe4e4411ac4a5fad9"
os = "windows"

    [[CasADi.download]]
    sha256 = "fab9537d53d6bba208d9676ad7d41fea1b702fadfdc8cd6e357e5d7ef9ed8c70"
    url = "https://github.com/JuliaBinaryWrappers/CasADi_jll.jl/releases/download/CasADi-v3.7.3+0/CasADi.v3.7.3.x86_64-w64-mingw32-cxx11.tar.gz"
