# Autogenerated wrapper script for CasADi_jll for aarch64-apple-darwin
export amplexe, libcasadi, libcasadi_conic_ipqp, libcasadi_conic_nlpsol, libcasadi_conic_qrqp, libcasadi_importer_shell, libcasadi_integrator_collocation, libcasadi_integrator_cvodes, libcasadi_integrator_idas, libcasadi_integrator_rk, libcasadi_interpolant_bspline, libcasadi_interpolant_linear, libcasadi_linsol_csparse, libcasadi_linsol_csparsecholesky, libcasadi_linsol_ldl, libcasadi_linsol_lsqr, libcasadi_linsol_qr, libcasadi_linsol_symbolicqr, libcasadi_linsol_tridiag, libcasadi_nlpsol_feasiblesqpmethod, libcasadi_nlpsol_ipopt, libcasadi_nlpsol_qrsqp, libcasadi_nlpsol_scpgen, libcasadi_nlpsol_sqpmethod, libcasadi_rootfinder_fast_newton, libcasadi_rootfinder_kinsol, libcasadi_rootfinder_newton, libcasadi_rootfinder_nlpsol, libcasadi_sundials_common, libcasadi_xmlfile_tinyxml

using CompilerSupportLibraries_jll
using Ipopt_jll
JLLWrappers.@generate_wrapper_header("CasADi")
JLLWrappers.@declare_library_product(libcasadi, "@rpath/libcasadi.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_conic_ipqp, "@rpath/libcasadi_conic_ipqp.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_conic_nlpsol, "@rpath/libcasadi_conic_nlpsol.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_conic_qrqp, "@rpath/libcasadi_conic_qrqp.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_importer_shell, "@rpath/libcasadi_importer_shell.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_integrator_collocation, "@rpath/libcasadi_integrator_collocation.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_integrator_cvodes, "@rpath/libcasadi_integrator_cvodes.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_integrator_idas, "@rpath/libcasadi_integrator_idas.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_integrator_rk, "@rpath/libcasadi_integrator_rk.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_interpolant_bspline, "@rpath/libcasadi_interpolant_bspline.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_interpolant_linear, "@rpath/libcasadi_interpolant_linear.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_linsol_csparse, "@rpath/libcasadi_linsol_csparse.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_linsol_csparsecholesky, "@rpath/libcasadi_linsol_csparsecholesky.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_linsol_ldl, "@rpath/libcasadi_linsol_ldl.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_linsol_lsqr, "@rpath/libcasadi_linsol_lsqr.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_linsol_qr, "@rpath/libcasadi_linsol_qr.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_linsol_symbolicqr, "@rpath/libcasadi_linsol_symbolicqr.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_linsol_tridiag, "@rpath/libcasadi_linsol_tridiag.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_feasiblesqpmethod, "@rpath/libcasadi_nlpsol_feasiblesqpmethod.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_ipopt, "@rpath/libcasadi_nlpsol_ipopt.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_qrsqp, "@rpath/libcasadi_nlpsol_qrsqp.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_scpgen, "@rpath/libcasadi_nlpsol_scpgen.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_sqpmethod, "@rpath/libcasadi_nlpsol_sqpmethod.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_fast_newton, "@rpath/libcasadi_rootfinder_fast_newton.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_kinsol, "@rpath/libcasadi_rootfinder_kinsol.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_newton, "@rpath/libcasadi_rootfinder_newton.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_nlpsol, "@rpath/libcasadi_rootfinder_nlpsol.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_sundials_common, "@rpath/libcasadi_sundials_common.3.7.dylib")
JLLWrappers.@declare_library_product(libcasadi_xmlfile_tinyxml, "@rpath/libcasadi_xmlfile_tinyxml.3.7.dylib")
JLLWrappers.@declare_executable_product(amplexe)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Ipopt_jll)
    JLLWrappers.@init_library_product(
        libcasadi,
        "lib/libcasadi.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_conic_ipqp,
        "lib/libcasadi_conic_ipqp.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_conic_nlpsol,
        "lib/libcasadi_conic_nlpsol.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_conic_qrqp,
        "lib/libcasadi_conic_qrqp.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_importer_shell,
        "lib/libcasadi_importer_shell.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_collocation,
        "lib/libcasadi_integrator_collocation.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_cvodes,
        "lib/libcasadi_integrator_cvodes.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_idas,
        "lib/libcasadi_integrator_idas.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_rk,
        "lib/libcasadi_integrator_rk.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_interpolant_bspline,
        "lib/libcasadi_interpolant_bspline.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_interpolant_linear,
        "lib/libcasadi_interpolant_linear.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_csparse,
        "lib/libcasadi_linsol_csparse.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_csparsecholesky,
        "lib/libcasadi_linsol_csparsecholesky.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_ldl,
        "lib/libcasadi_linsol_ldl.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_lsqr,
        "lib/libcasadi_linsol_lsqr.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_qr,
        "lib/libcasadi_linsol_qr.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_symbolicqr,
        "lib/libcasadi_linsol_symbolicqr.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_tridiag,
        "lib/libcasadi_linsol_tridiag.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_feasiblesqpmethod,
        "lib/libcasadi_nlpsol_feasiblesqpmethod.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_ipopt,
        "lib/libcasadi_nlpsol_ipopt.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_qrsqp,
        "lib/libcasadi_nlpsol_qrsqp.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_scpgen,
        "lib/libcasadi_nlpsol_scpgen.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_sqpmethod,
        "lib/libcasadi_nlpsol_sqpmethod.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_fast_newton,
        "lib/libcasadi_rootfinder_fast_newton.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_kinsol,
        "lib/libcasadi_rootfinder_kinsol.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_newton,
        "lib/libcasadi_rootfinder_newton.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_nlpsol,
        "lib/libcasadi_rootfinder_nlpsol.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_sundials_common,
        "lib/libcasadi_sundials_common.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_xmlfile_tinyxml,
        "lib/libcasadi_xmlfile_tinyxml.3.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        amplexe,
        "bin/amplexe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
