# Autogenerated wrapper script for CasADi_jll for i686-w64-mingw32-cxx11
export amplexe, libcasadi, libcasadi_conic_ipqp, libcasadi_conic_nlpsol, libcasadi_conic_qrqp, libcasadi_importer_shell, libcasadi_integrator_collocation, libcasadi_integrator_cvodes, libcasadi_integrator_idas, libcasadi_integrator_rk, libcasadi_interpolant_bspline, libcasadi_interpolant_linear, libcasadi_linsol_csparse, libcasadi_linsol_csparsecholesky, libcasadi_linsol_ldl, libcasadi_linsol_lsqr, libcasadi_linsol_qr, libcasadi_linsol_symbolicqr, libcasadi_linsol_tridiag, libcasadi_nlpsol_feasiblesqpmethod, libcasadi_nlpsol_ipopt, libcasadi_nlpsol_qrsqp, libcasadi_nlpsol_scpgen, libcasadi_nlpsol_sqpmethod, libcasadi_rootfinder_fast_newton, libcasadi_rootfinder_kinsol, libcasadi_rootfinder_newton, libcasadi_rootfinder_nlpsol, libcasadi_sundials_common, libcasadi_xmlfile_tinyxml

using CompilerSupportLibraries_jll
using Ipopt_jll
JLLWrappers.@generate_wrapper_header("CasADi")
JLLWrappers.@declare_library_product(libcasadi, "libcasadi.dll")
JLLWrappers.@declare_library_product(libcasadi_conic_ipqp, "libcasadi_conic_ipqp.dll")
JLLWrappers.@declare_library_product(libcasadi_conic_nlpsol, "libcasadi_conic_nlpsol.dll")
JLLWrappers.@declare_library_product(libcasadi_conic_qrqp, "libcasadi_conic_qrqp.dll")
JLLWrappers.@declare_library_product(libcasadi_importer_shell, "libcasadi_importer_shell.dll")
JLLWrappers.@declare_library_product(libcasadi_integrator_collocation, "libcasadi_integrator_collocation.dll")
JLLWrappers.@declare_library_product(libcasadi_integrator_cvodes, "libcasadi_integrator_cvodes.dll")
JLLWrappers.@declare_library_product(libcasadi_integrator_idas, "libcasadi_integrator_idas.dll")
JLLWrappers.@declare_library_product(libcasadi_integrator_rk, "libcasadi_integrator_rk.dll")
JLLWrappers.@declare_library_product(libcasadi_interpolant_bspline, "libcasadi_interpolant_bspline.dll")
JLLWrappers.@declare_library_product(libcasadi_interpolant_linear, "libcasadi_interpolant_linear.dll")
JLLWrappers.@declare_library_product(libcasadi_linsol_csparse, "libcasadi_linsol_csparse.dll")
JLLWrappers.@declare_library_product(libcasadi_linsol_csparsecholesky, "libcasadi_linsol_csparsecholesky.dll")
JLLWrappers.@declare_library_product(libcasadi_linsol_ldl, "libcasadi_linsol_ldl.dll")
JLLWrappers.@declare_library_product(libcasadi_linsol_lsqr, "libcasadi_linsol_lsqr.dll")
JLLWrappers.@declare_library_product(libcasadi_linsol_qr, "libcasadi_linsol_qr.dll")
JLLWrappers.@declare_library_product(libcasadi_linsol_symbolicqr, "libcasadi_linsol_symbolicqr.dll")
JLLWrappers.@declare_library_product(libcasadi_linsol_tridiag, "libcasadi_linsol_tridiag.dll")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_feasiblesqpmethod, "libcasadi_nlpsol_feasiblesqpmethod.dll")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_ipopt, "libcasadi_nlpsol_ipopt.dll")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_qrsqp, "libcasadi_nlpsol_qrsqp.dll")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_scpgen, "libcasadi_nlpsol_scpgen.dll")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_sqpmethod, "libcasadi_nlpsol_sqpmethod.dll")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_fast_newton, "libcasadi_rootfinder_fast_newton.dll")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_kinsol, "libcasadi_rootfinder_kinsol.dll")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_newton, "libcasadi_rootfinder_newton.dll")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_nlpsol, "libcasadi_rootfinder_nlpsol.dll")
JLLWrappers.@declare_library_product(libcasadi_sundials_common, "libcasadi_sundials_common.dll")
JLLWrappers.@declare_library_product(libcasadi_xmlfile_tinyxml, "libcasadi_xmlfile_tinyxml.dll")
JLLWrappers.@declare_executable_product(amplexe)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Ipopt_jll)
    JLLWrappers.@init_library_product(
        libcasadi,
        "bin\\libcasadi.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_conic_ipqp,
        "bin\\libcasadi_conic_ipqp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_conic_nlpsol,
        "bin\\libcasadi_conic_nlpsol.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_conic_qrqp,
        "bin\\libcasadi_conic_qrqp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_importer_shell,
        "bin\\libcasadi_importer_shell.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_collocation,
        "bin\\libcasadi_integrator_collocation.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_cvodes,
        "bin\\libcasadi_integrator_cvodes.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_idas,
        "bin\\libcasadi_integrator_idas.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_rk,
        "bin\\libcasadi_integrator_rk.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_interpolant_bspline,
        "bin\\libcasadi_interpolant_bspline.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_interpolant_linear,
        "bin\\libcasadi_interpolant_linear.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_csparse,
        "bin\\libcasadi_linsol_csparse.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_csparsecholesky,
        "bin\\libcasadi_linsol_csparsecholesky.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_ldl,
        "bin\\libcasadi_linsol_ldl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_lsqr,
        "bin\\libcasadi_linsol_lsqr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_qr,
        "bin\\libcasadi_linsol_qr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_symbolicqr,
        "bin\\libcasadi_linsol_symbolicqr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_tridiag,
        "bin\\libcasadi_linsol_tridiag.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_feasiblesqpmethod,
        "bin\\libcasadi_nlpsol_feasiblesqpmethod.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_ipopt,
        "bin\\libcasadi_nlpsol_ipopt.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_qrsqp,
        "bin\\libcasadi_nlpsol_qrsqp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_scpgen,
        "bin\\libcasadi_nlpsol_scpgen.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_sqpmethod,
        "bin\\libcasadi_nlpsol_sqpmethod.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_fast_newton,
        "bin\\libcasadi_rootfinder_fast_newton.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_kinsol,
        "bin\\libcasadi_rootfinder_kinsol.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_newton,
        "bin\\libcasadi_rootfinder_newton.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_nlpsol,
        "bin\\libcasadi_rootfinder_nlpsol.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_sundials_common,
        "bin\\libcasadi_sundials_common.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_xmlfile_tinyxml,
        "bin\\libcasadi_xmlfile_tinyxml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        amplexe,
        "bin\\amplexe.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
