# Autogenerated wrapper script for CasADi_jll for i686-linux-musl-cxx11
export amplexe, libcasadi, libcasadi_conic_ipqp, libcasadi_conic_nlpsol, libcasadi_conic_qrqp, libcasadi_importer_shell, libcasadi_integrator_collocation, libcasadi_integrator_cvodes, libcasadi_integrator_idas, libcasadi_integrator_rk, libcasadi_interpolant_bspline, libcasadi_interpolant_linear, libcasadi_linsol_csparse, libcasadi_linsol_csparsecholesky, libcasadi_linsol_ldl, libcasadi_linsol_lsqr, libcasadi_linsol_qr, libcasadi_linsol_symbolicqr, libcasadi_linsol_tridiag, libcasadi_nlpsol_feasiblesqpmethod, libcasadi_nlpsol_ipopt, libcasadi_nlpsol_qrsqp, libcasadi_nlpsol_scpgen, libcasadi_nlpsol_sqpmethod, libcasadi_rootfinder_fast_newton, libcasadi_rootfinder_kinsol, libcasadi_rootfinder_newton, libcasadi_rootfinder_nlpsol, libcasadi_sundials_common, libcasadi_xmlfile_tinyxml

using CompilerSupportLibraries_jll
using Ipopt_jll
JLLWrappers.@generate_wrapper_header("CasADi")
JLLWrappers.@declare_library_product(libcasadi, "libcasadi.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_conic_ipqp, "libcasadi_conic_ipqp.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_conic_nlpsol, "libcasadi_conic_nlpsol.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_conic_qrqp, "libcasadi_conic_qrqp.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_importer_shell, "libcasadi_importer_shell.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_integrator_collocation, "libcasadi_integrator_collocation.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_integrator_cvodes, "libcasadi_integrator_cvodes.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_integrator_idas, "libcasadi_integrator_idas.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_integrator_rk, "libcasadi_integrator_rk.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_interpolant_bspline, "libcasadi_interpolant_bspline.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_interpolant_linear, "libcasadi_interpolant_linear.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_linsol_csparse, "libcasadi_linsol_csparse.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_linsol_csparsecholesky, "libcasadi_linsol_csparsecholesky.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_linsol_ldl, "libcasadi_linsol_ldl.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_linsol_lsqr, "libcasadi_linsol_lsqr.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_linsol_qr, "libcasadi_linsol_qr.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_linsol_symbolicqr, "libcasadi_linsol_symbolicqr.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_linsol_tridiag, "libcasadi_linsol_tridiag.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_feasiblesqpmethod, "libcasadi_nlpsol_feasiblesqpmethod.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_ipopt, "libcasadi_nlpsol_ipopt.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_qrsqp, "libcasadi_nlpsol_qrsqp.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_scpgen, "libcasadi_nlpsol_scpgen.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_nlpsol_sqpmethod, "libcasadi_nlpsol_sqpmethod.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_fast_newton, "libcasadi_rootfinder_fast_newton.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_kinsol, "libcasadi_rootfinder_kinsol.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_newton, "libcasadi_rootfinder_newton.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_rootfinder_nlpsol, "libcasadi_rootfinder_nlpsol.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_sundials_common, "libcasadi_sundials_common.so.3.7")
JLLWrappers.@declare_library_product(libcasadi_xmlfile_tinyxml, "libcasadi_xmlfile_tinyxml.so.3.7")
JLLWrappers.@declare_executable_product(amplexe)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Ipopt_jll)
    JLLWrappers.@init_library_product(
        libcasadi,
        "lib/libcasadi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_conic_ipqp,
        "lib/libcasadi_conic_ipqp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_conic_nlpsol,
        "lib/libcasadi_conic_nlpsol.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_conic_qrqp,
        "lib/libcasadi_conic_qrqp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_importer_shell,
        "lib/libcasadi_importer_shell.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_collocation,
        "lib/libcasadi_integrator_collocation.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_cvodes,
        "lib/libcasadi_integrator_cvodes.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_idas,
        "lib/libcasadi_integrator_idas.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_integrator_rk,
        "lib/libcasadi_integrator_rk.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_interpolant_bspline,
        "lib/libcasadi_interpolant_bspline.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_interpolant_linear,
        "lib/libcasadi_interpolant_linear.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_csparse,
        "lib/libcasadi_linsol_csparse.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_csparsecholesky,
        "lib/libcasadi_linsol_csparsecholesky.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_ldl,
        "lib/libcasadi_linsol_ldl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_lsqr,
        "lib/libcasadi_linsol_lsqr.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_qr,
        "lib/libcasadi_linsol_qr.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_symbolicqr,
        "lib/libcasadi_linsol_symbolicqr.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_linsol_tridiag,
        "lib/libcasadi_linsol_tridiag.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_feasiblesqpmethod,
        "lib/libcasadi_nlpsol_feasiblesqpmethod.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_ipopt,
        "lib/libcasadi_nlpsol_ipopt.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_qrsqp,
        "lib/libcasadi_nlpsol_qrsqp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_scpgen,
        "lib/libcasadi_nlpsol_scpgen.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_nlpsol_sqpmethod,
        "lib/libcasadi_nlpsol_sqpmethod.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_fast_newton,
        "lib/libcasadi_rootfinder_fast_newton.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_kinsol,
        "lib/libcasadi_rootfinder_kinsol.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_newton,
        "lib/libcasadi_rootfinder_newton.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_rootfinder_nlpsol,
        "lib/libcasadi_rootfinder_nlpsol.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_sundials_common,
        "lib/libcasadi_sundials_common.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcasadi_xmlfile_tinyxml,
        "lib/libcasadi_xmlfile_tinyxml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        amplexe,
        "bin/amplexe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
